### ISSUE TITLE
Unable to install plugin into Ionic project

### ISSUE THREAD

**Issue by maxg7** [timflapper/cordova-spotify-plugin#1] opened 2014-06-24 17:29 UTC
When trying to install the plugin into an Ionic project (ionicframework.com) I'm receiving the following stacktrace error. Plugman is installed, as it appears to be required. I haven't yet tried installing it separately and then migrating the instal into an Ionic project.

Stack trace below
-------

$ cordova plugin add https://github.com/timflapper/cordova-spotify-plugin

Fetching plugin "https://github.com/timflapper/cordova-spotify-plugin" via git clone

SyntaxError: Unexpected token ]

    at Object.parse (native)

    at Object.get_platform_json (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/config-changes.js:426:31)

    at isPluginInstalled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:617:42)

    at runInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:243:9)

    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:55:16

    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:798:54)

    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:827:30)

    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:760:13)

    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:821:14

    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)

**Comment by timmil** [comment] 2015-01-15 14:27
Having this same problem, did you ever resolve it?

**Comment by maxg7** [comment] 2015-01-15 14:49
Yeah, I was able to resolve that. Thanks for checking.

**Comment by timmil** [comment] 2015-01-15 15:16
...how?

**Comment by timflapper** [comment] 2015-01-15 16:23
@timmil, The `master` is actually broken currently because of updates on the Spotify API itself. The `dev` branch does work but needs some finetuning before I'm willing to merge it to master and make a release out of it. 

I tried installing the `dev` branch version to a new Ionic project and that seemed to work for me.

**Comment by maxg7** [comment] 2015-01-15 16:24
Ah, for a second I thought you were Tim F, the creator of the
cordova-spotify-plugin.

As far as installing it into an ionic project, using the dev branch (which
is compatible with the latest spotify sdk) the installation worked almost
without fail. There was one or two tweaks I made to the install.sh script
to use the new beta-6.targ.gz that I hadn't merged back into the repo.

That said, once it installed I wasn't able to actually call into the
plugins in the same way Tim F did in his tests. I tried a bunch of
different ways to reference the library but none of them seemed to work. In
a separate email chain Tim F said he was going to go through and make a
simple example project shortly. That was on the 10th.

**Comment by timflapper** [comment] 2015-01-15 16:25
That example project is coming. Just need to find the time :smile:

**Comment by timflapper** [comment] 2015-01-31 03:32
[v 0.1.0](https://github.com/timflapper/cordova-spotify-plugin/releases/tag/v0.1.0) has just been released. A lot of issues that where still haunting the `dev` branch have been solved. I got it working without a hitch inside a new Cordova project. Can you check if it this latest version works for you in Ionic?

Unfortunately the API documentation is horribly out-of-date and inaccurate. The specs are probably the best source of documentation at this moment. Below is a short example that should work in a newly created cordova project (`cordova create hello com.hello.world HelloWorld`).

#### Quick start in Vanilla Cordova

Replace the code inside `index.js` with the following:

```javascript
var session, player;

var urlScheme = 'your-custom-url-scheme';
var clientId = 'your-own-client-id';

function onDeviceReady() {
  spotify.authenticate(urlScheme, clientId, 'token', authDone);
}

function authDone(error, sess) {
  if (error) return console.log("ERROR!", error);

  console.log(sess);

  session = sess;

  player = spotify.createAudioPlayer(clientId);

  player.login(session, function(error) {
    if (error) return console.log(error);

    player.play('spotify:track:2DlfLPbXH5ncf56Nytxd4w', function(error) {
      if (error) return console.log(error);
    });
  });
}

document.addEventListener('deviceready', onDeviceReady, false);
```

Because the example uses `token` instead of `code` as responseType, you don't need to setup a token swap service. Sessions created this way will however only be valid for one hour.

**Comment by timflapper** [comment] 2015-01-31 09:47
I'm closing this issue because it seems to be resolved with the latest versions of Cordova and Ionic.

**Closed by timflapper** 2015-01-31 09:47 UTC

**Comment by ciriac** [comment] 2015-08-26 21:10
I know this issue is closed but I have one question regarding your example code posted above. I tried following your example, after authenticating on the spotify page I get this error "Invalid client: Invalid redirect URI".

Do I need to create a redirect URI on https://developer.spotify.com/my-applications? If so, where does this URI go in your example code?

Thank you for providing this plugin. Is the example project still coming? It would really be useful.

**Comment by frey1esm** [comment] 2015-09-03 12:23
I also am not making the round trip because of the urlSheme. I am getting Safari error "Cannot Open Page" after entering correct username/password in Spotify authorization screen.

I have my urlSheme exactly as setup when I installed the plugin:  'myapp-spotify'   and I have it whitelisted in Spotify as   myapp-spotify://

Where/how do we create a redirect url so that we can specify the "page" that opens in our app?

**Comment by timflapper** [comment] 2015-09-03 13:22
@frey1esm, you should whitelist `myapp-spotify://callback`. This will be the url that the website will redirect back to.

**Comment by timflapper** [comment] 2015-09-03 13:24
@ciriac, the uri will be automatically setup by the install script once you set a uri-scheme. See @frey1esm's message for an example. You don't need to add the `://` but just the `myapp-spotify` part. Then the url you need to whitelist in the spotify developers portal will be `myapp-spotify://callback`.

**Comment by frey1esm** [comment] 2015-09-04 20:09
@timflapper - Not sure if this is a plugin issue or a Spotify SDK issue, but here's what happens. My app opens the spotify login screen just fine. Once my username and password are submitted, the app (Safari) attempt to open the following URL and fails right there (my client Id has been replaced with Xs to protect the innocent):

`https://accounts.spotify.com/en/login?continue=https:%2F%2Faccounts.spotify.com%2Fen%2Fauthorize%3Fclient_id%3DXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX%26scope%3Dstreaming%26redirect_uri%3Dmyapp-spotify:%252F%252Fcallback%26download_prompt%3Dtrue%26response_type%3Dtoken`

Does this URL look legit ?

**Comment by timflapper** [comment] 2015-09-07 10:29
@frey1esm, that looks okay. You should make sure the URL type is registered to your iOS app correctly. If the configuration is incorrect, iOS won't be able to link your app with the `myapp-spotify` protocol.

**Comment by frey1esm** [comment] 2015-09-10 13:00
@timflapper - My settings in Xcode --> Info --> URL Types are:

Identifier = Spotify Auth
URL Schemes = myapp-spotify
Role = Editor

Are these correct?

**Comment by ciriac** [comment] 2015-09-27 18:24
@frey1esm, I can confirm that this solves the issue. Thanks @timflapper!
